$ErrorActionPreference = "Stop"
$root = Resolve-Path (Join-Path $PSScriptRoot "..")
$scratch = Join-Path ([IO.Path]::GetTempPath()) "spiral-optical-correlation-$([guid]::NewGuid().ToString('N'))"
New-Item -ItemType Directory -Force -Path $scratch | Out-Null
try {
    $marker = Join-Path $scratch "marker.json"; $observation = Join-Path $scratch "observation.json"; $receipt = Join-Path $scratch "receipt.json"
    '{"schema":1,"runId":"run-7","processId":7,"executablePath":"C:\\Editor.exe","qpcFrequency":10000000,"qpcTick":7,"markerId":"marker-7","triggerId":"synthetic-7","frame":7,"inputFrame":7,"inputQpc":7,"backend":"NVRHI D3D12","requestedPresentationMode":"Synchronized","actualPresentationMode":"D3D12FlipSynchronized","presentationGeneration":1,"unavailable":{"clickToPhoton":"unavailable"}}' | Set-Content -NoNewline $marker
    '{"source":"Photodiode","runId":"run-7","processId":7,"executablePath":"C:\\Editor.exe","qpcFrequency":10000000,"markerId":"marker-7","triggerId":"synthetic-7","frame":7,"inputFrame":7,"timingDomain":"calibrated-camera-clock","observedMilliseconds":1.25}' | Set-Content -NoNewline $observation
    & (Join-Path $root "Scripts\WriteOpticalInputCorrelationReceipt.ps1") -MarkerPath $marker -ObservationPath $observation -ReceiptPath $receipt -Method Photodiode -Device "test-diode" -Calibration "test-calibration" -Monitor "test-monitor" -Connection "test-connection" -OsRefresh "test-refresh" -DriverDisplayState "test-driver"
    $ok = Get-Content -Raw $receipt | ConvertFrom-Json
    if ($ok.status -ne "completed" -or $ok.marker.frame -ne 7 -or $ok.observation.markerId -ne "marker-7" -or [string]::IsNullOrWhiteSpace([string]$ok.rawObservationSha256) -or $ok.unavailable.clickToPhoton -ne "unavailable") { throw "Successful receipt omitted exact identity, raw hash, or unavailable truthfulness." }
    Remove-Item -LiteralPath $receipt -Force
    '{"source":"PresentMon","runId":"run-7","processId":7,"executablePath":"C:\\Editor.exe","qpcFrequency":10000000,"markerId":"marker-7","triggerId":"synthetic-7","frame":7,"inputFrame":7,"timingDomain":"fake","observedMilliseconds":1.25}' | Set-Content -NoNewline $observation
    $failed = $false; try { & (Join-Path $root "Scripts\WriteOpticalInputCorrelationReceipt.ps1") -MarkerPath $marker -ObservationPath $observation -ReceiptPath $receipt -Method Photodiode -Device "test-diode" -Calibration "test-calibration" -Monitor "test-monitor" -Connection "test-connection" -OsRefresh "test-refresh" -DriverDisplayState "test-driver" } catch { $failed = $true }
    $bad = Get-Content -Raw $receipt | ConvertFrom-Json
    if (!$failed -or $bad.status -ne "failed" -or [string]::IsNullOrWhiteSpace([string]$bad.failure) -or $bad.cleanup.operatorOwnedDevice -ne "not-owned") { throw "Surrogate rejection did not publish a fail-closed cleanup receipt." }
    foreach ($case in @('{"source":"Photodiode","runId":"stale","processId":7,"executablePath":"C:\\Editor.exe","qpcFrequency":10000000,"markerId":"marker-7","triggerId":"synthetic-7","frame":7,"inputFrame":7,"timingDomain":"clock","observedMilliseconds":1}', '{"source":"Photodiode","runId":"run-7","processId":7,"executablePath":"C:\\Editor.exe","qpcFrequency":10000000,"markerId":"marker-7","triggerId":"synthetic-7","frame":7,"inputFrame":7,"timingDomain":"clock","observedMilliseconds":1,"duplicate":true}', '{"source":"Photodiode","runId":"run-7","processId":7,"executablePath":"C:\\Editor.exe","qpcFrequency":10000000,"markerId":"marker-7","triggerId":"synthetic-7","frame":7,"inputFrame":7,"timingDomain":"clock","observedMilliseconds":1,"ambiguous":true}', '{"source":"Photodiode","runId":"run-7","processId":7,"executablePath":"C:\\Editor.exe","qpcFrequency":10000000,"markerId":"marker-7","triggerId":"synthetic-7","frame":7,"inputFrame":7,"timingDomain":"clock","observedMilliseconds":-1}')) {
        Remove-Item -LiteralPath $receipt -Force; $case | Set-Content -NoNewline $observation; $rejected = $false; try { & (Join-Path $root "Scripts\WriteOpticalInputCorrelationReceipt.ps1") -MarkerPath $marker -ObservationPath $observation -ReceiptPath $receipt -Method Photodiode -Device "test-diode" -Calibration "test-calibration" -Monitor "test-monitor" -Connection "test-connection" -OsRefresh "test-refresh" -DriverDisplayState "test-driver" } catch { $rejected = $true }; if (!$rejected -or (Get-Content -Raw $receipt | ConvertFrom-Json).status -ne "failed") { throw "Malformed, stale, duplicate, or noncausal observation was accepted." }
    }
    Remove-Item -LiteralPath $observation -Force; Remove-Item -LiteralPath $receipt -Force
    $failed = $false; try { & (Join-Path $root "Scripts\WriteOpticalInputCorrelationReceipt.ps1") -MarkerPath $marker -ObservationPath $observation -ReceiptPath $receipt -Method Photodiode -Device "test-diode" -Calibration "test-calibration" -Monitor "test-monitor" -Connection "test-connection" -OsRefresh "test-refresh" -DriverDisplayState "test-driver" -TimeoutMilliseconds 100 } catch { $failed = $true }
    $timeout = Get-Content -Raw $receipt | ConvertFrom-Json
    if (!$failed -or $timeout.status -ne "failed" -or $timeout.failure -notmatch "timed out" -or $timeout.cleanup.operatorOwnedDevice -ne "not-owned") { throw "Timeout did not publish truthful fail-closed cleanup." }
    $collision = $false; try { & (Join-Path $root "Scripts\WriteOpticalInputCorrelationReceipt.ps1") -MarkerPath $marker -ObservationPath $observation -ReceiptPath $receipt -Method Photodiode -Device "test-diode" -Calibration "test-calibration" -Monitor "test-monitor" -Connection "test-connection" -OsRefresh "test-refresh" -DriverDisplayState "test-driver" -TimeoutMilliseconds 100 } catch { $collision = $true }
    if (!$collision) { throw "Existing receipt collision was overwritten." }
    Write-Host "OpticalInputCorrelationV1 result=pass cases=exact-identity,unavailable,malformed-stale-duplicate-noncausal,surrogate-rejection,timeout-cleanup,receipt-collision"
} finally { Remove-Item -LiteralPath $scratch -Recurse -Force -ErrorAction SilentlyContinue }
